let listaProductos=[
    {
        id: 1,
        nombre: 'World of Warcraft',
        imagenLogo: '/imagenes/world-of-warcraft.jpg',
        compatibilidad: ["fa-solid fa-desktop"],
        precio: '$5.000',
        descuento: '40%',
    },
    {
        id: 2,
        nombre: 'Gran Turismo',
        imagenLogo: '/imagenes/gran-turismo.jpg',
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox"],
        precio: '$12.400',
        descuento: '20%',
    },
    {
        id: 3,
        nombre: 'Stardew Valley',
        imagenLogo: '/imagenes/stardew-valley.jpg',
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox","fa-brands fa-apple","fa-brands fa-android"],
        precio: '$3.750',
        descuento: '67%',
    },
    {
        id: 4,
        nombre: 'League Of Legends',
        imagenLogo: '/imagenes/league-of-legends.jpg',
        compatibilidad: ["fa-solid fa-desktop"],
        precio: '$3.750',
        descuento: '67%',
    },
    {
        id: 5,
        nombre: 'Minecraft',
        imagenLogo: '/imagenes/minecraft.jpeg',
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox","fa-brands fa-apple","fa-brands fa-android"],
        precio: '$3.750',
        descuento: '67%',
    },
    {
        id: 6,
        nombre: 'Left For Dead 2',
        imagenLogo: '/imagenes/left-for-dead-2.jpg',
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox"],
        precio: '129$',
        descuento: '25%',
    },
    {
        id: 7,
        nombre: 'Elden Ring',
        imagenLogo: '/imagenes/elden-ring.jpg',
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox"],
        precio: '4.999$',
        descuento: '10%',
    },
    {
        id: 8,
        nombre: 'Raft',
        imagenLogo: '/imagenes/raft.jpg',
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox"],
        precio: '224$',
        descuento: '15%',
    },
    {
        id: 9,
        nombre: 'Terraria',
        imagenLogo: '/imagenes/terraria.jpg',
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox","fa-brands fa-apple","fa-brands fa-android"],
        precio: '3.750$',
        descuento: '67%',
    },
    {
        id: 10,
        nombre: 'Fifa 2022',
        imagenLogo: '/imagenes/fifa2022-2.jpg',
        imagenes: ['/imagenes/fifa2022-3.jpg', '/imagenes/fifa2022-4.jpg', '/imagenes/fifa2022-5.jpg', '/imagenes/fifa2022-6.jpg', '/imagenes/fifa2022-7.jpg'],
        compatibilidad: ["fa-solid fa-desktop","fa-brands fa-playstation","fa-brands fa-xbox"],
        precio: '5.499$',
        descuento: '10%',
    },
]

module.exports = listaProductos;